version: '3'
services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    init: true
    volumes:
      - wordpress_files:/var/www/html/wordpress
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - wordpress
    env_file:
      - .env
    restart: always
    init: true
    volumes:
      - wordpress_db:/var/lib/mysql/
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - wordpress
    depends_on:
      - wordpress
      - mariadb
    env_file:
      - .env
    restart: always
    init: true
    volumes:
      - wordpress_files:/var/www/html/wordpress
volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: /home/abaioumy/data/mariadb
      o: bind
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/abaioumy/data/wordpress
      o: bind
networks:
  wordpress:
